### ISSUE TITLE
目录

### ISSUE THREAD

**Issue by sunyanhui123** [sunyanhui123/note#1]
要找工作了，整理记录一下面试题，程序员要看的东西真尼玛多

- java基础

> [泛型](https://github.com/sunyanhui123/interview/issues/10#issue-400084370)
[动态代理](https://github.com/sunyanhui123/interview/issues/11#issue-400139822)
[注解](https://github.com/sunyanhui123/interview/issues/12#issue-400169986)
[java数组](https://github.com/sunyanhui123/interview/issues/22#issue-412219018)
[java集合介绍](https://github.com/sunyanhui123/interview/issues/24#issue-412258631)
[ArrayList](https://github.com/sunyanhui123/interview/issues/23#issue-412229396)
[LinkedList](https://github.com/sunyanhui123/interview/issues/25#issue-412267912)
设计模式

- java多线程编程

> [几种阻塞方法](https://github.com/sunyanhui123/interview/issues/6#issue-399663018)
[Sychronize](https://github.com/sunyanhui123/interview/issues/7#issue-399681686)
[cas](https://github.com/sunyanhui123/interview/issues/16#issue-409606702)
[java内存模型](https://github.com/sunyanhui123/interview/issues/17#issue-409609164)
[concurrent包介绍](https://github.com/sunyanhui123/interview/issues/15#issue-409604209)
[AQS](https://github.com/sunyanhui123/interview/issues/19#issue-410158841)
[单利模式](https://github.com/sunyanhui123/interview/issues/21#issue-411721408)
[CopyOnWriteArrayList](https://github.com/sunyanhui123/interview/issues/26#issue-412271532)
[HashMap与ConcurrentHashMap](https://github.com/sunyanhui123/interview/issues/27#issue-412275288)

- 数据结构

> 二叉树
B-tree
B+tree
红黑树
跳表
左右值
十大排序算法

- 数据库

> [索引](https://blog.csdn.net/ifollowrivers/article/details/73614549)
[数据库事物隔离级别](https://github.com/sunyanhui123/note/issues/4#issue-399319103)
数据存储的文件结构
索引文件结构
sql优化
[数据库log](https://github.com/sunyanhui123/note/issues/5#issue-399630852)
问题排查

- java容器

> 常用集合类
java8中Streams

- JVM
 

> jvm

- IO

> bio、nio、aio
netty、epoll

- 常见面试题

> [JSP与html区别](https://github.com/sunyanhui123/interview/issues/9#issue-400075407)

- 中间件框架

> zookeeper
dubbo
kafka
[tomcat](https://github.com/sunyanhui123/interview/issues/28#issue-414485852)
spring cloud
[docker](https://yuedu.baidu.com/ebook/d817967416fc700abb68fca1?pn=1&rf=https%3A%2F%2Fyuedu.baidu.com%2Febook%2Fd817967416fc700abb68fca1&tdsourcetag=s_pctim_aiomsg&qq-pf-to=pcqq.c2c)

- 网络

> [tcp协议](https://github.com/sunyanhui123/note/issues/3#issue-399208210)

- 缓存专题
![image](https://user-images.githubusercontent.com/13620100/51243119-a851f400-19bc-11e9-8630-d06c4e39c36b.png)

- 消息队列专题
![image](https://user-images.githubusercontent.com/13620100/51243329-375f0c00-19bd-11e9-8d6b-b1deb3c9e961.png)

- 分布式

> [分布式事务](https://github.com/sunyanhui123/interview/issues/13#issue-400182193)

https://www.cnblogs.com/duanxz/p/5229352.html

http://www.ruanyifeng.com/blog/2007/10/ascii_unicode_and_utf-8.html?tdsourcetag=s_pctim_aiomsg
https://javadoop.com/

**Comment by woshiguodegang** [comment]
你好，我在github上搜“HashMap集合有关的面试题集”后翻到了你的博客，对你的博客排版很感兴趣，点进java基础里面的java集合介绍后，感觉进入了一个小世界，很简洁，发现在github里面写博客还能这样写；我试着谷歌怎么reference a issue，可是我描述的不清楚，搜出的结果不理想；我最近用github写博客，不怎么会用，所以你能教教我吗？万分感谢！我对github不熟悉，如果方便的的话发邮件至1986733968@qq.com，谢谢了！如有打扰，请谅解。
